config/routes.rb
Thacker::Application.routes.draw do
  resources :projects

  resources :events

  devise_for :admins
  devise_for :users

  resources :posts

  root :to => 'application#livestream'
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/event.rb
class Event < ActiveRecord::Base
  validates_presence_of :name, :author, :about
  belongs_to :author, :class_name => "User"

  after_create :create_live_stream

  private

  def create_live_stream
    EventLiveStream.create! :event_id => id, :user => author
  end
end

app/models/event_live_stream.rb
class EventLiveStream < LiveStream
  validates_presence_of :event
end

app/models/live_stream.rb
class LiveStream < ActiveRecord::Base
  belongs_to :user
  belongs_to :project
  belongs_to :post
  belongs_to :event

  validates_presence_of :user

  default_scope :order => "id DESC"

  def type
    self.class.name.tableize.split("_")[0]
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :title, :body, :user

  after_create :create_live_stream

  private

  def create_live_stream
    PostLiveStream.create! :post_id => id, :user => user
  end
end

app/models/post_live_stream.rb
class PostLiveStream < LiveStream
  validates_presence_of :post
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :author, :class_name => "User"
  belongs_to :status
end

app/models/project_live_stream.rb
class ProjectLiveStream < LiveStream
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  after_create :create_live_stream

  private

  def create_live_stream
    UserLiveStream.create! :user_id => id
  end
end

app/models/user_live_stream.rb
class UserLiveStream < LiveStream
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def livestream
    @stream = LiveStream.all
  end
end

app/controllers/events_controller.rb
class EventsController < InheritedResources::Base
end

app/controllers/posts_controller.rb
class PostsController < InheritedResources::Base
  before_filter :authenticate_user!, :only => :new
  before_filter :set_user, :only => :create


  private

  def set_user
    params[:post][:user] = current_user
  end

end

app/controllers/projects_controller.rb
class ProjectsController < InheritedResources::Base
end

app/views/application/livestream.html.haml
= content_for :title do
  Livestream

%ul
  - @stream.each do |status|
    = render "shared/stream/#{status.type}", :stream => status

app/views/events/_form.html.haml
= form_for @event do |f|
  -if @event.errors.any?
    #error_explanation
      %h2= "#{pluralize(@event.errors.count, "error")} prohibited this event from being saved:"
      %ul
        - @event.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :about
    = f.text_area :about
  .field
    = f.label :author
    = f.text_field :author
  .field
    = f.label :skills
    = f.text_area :skills
  .field
    = f.label :address
    = f.text_field :address
  .actions
    = f.submit 'Save'

app/views/events/edit.html.haml
%h1 Editing event

= render 'form'

= link_to 'Show', @event
\|
= link_to 'Back', events_path

app/views/events/index.html.haml
%h1 Listing events

%table
  %tr
    %th Name
    %th About
    %th Author
    %th Skills
    %th Address
    %th
    %th
    %th

  - @events.each do |event|
    %tr
      %td= event.name
      %td= event.about
      %td= event.author.name
      %td= event.skills
      %td= event.address
      %td= link_to 'Show', event
      %td= link_to 'Edit', edit_event_path(event)
      %td= link_to 'Destroy', event, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Event', new_event_path

app/views/events/new.html.haml
%h1 New event

= render 'form'

= link_to 'Back', events_path

app/views/events/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @event.name
%p
  %b About:
  = @event.about
%p
  %b Author:
  = @event.author
%p
  %b Skills:
  = @event.skills
%p
  %b Address:
  = @event.address

= link_to 'Edit', edit_event_path(@event)
\|
= link_to 'Back', events_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= content_for?(:title) ? "#{content_for(:title)} | Tranparência Hacker" : "Tranparência Hacker"
    = stylesheet_link_tag    "application"
    = csrf_meta_tags
  %body
    %div
      %header
        %h1= link_to "THacker", root_path
        %nav
          %ul
            %li= link_to "Blog", posts_path
            %li= link_to "Eventos", events_path
            %li= link_to "Membros", "#"
            %li= link_to "Projetos", projects_path
      #content= yield
      %footer
    = yield :javascripts
    = javascript_include_tag "application"

app/views/posts/_form.html.haml
= form_for @post do |f|
  -if @post.errors.any?
    #error_explanation
      %h2= "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:"
      %ul
        - @post.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :body
    = f.text_area :body
  .actions
    = f.submit 'Save'

app/views/posts/edit.html.haml
%h1 Editing post

= render 'form'

= link_to 'Show', @post
\|
= link_to 'Back', posts_path

app/views/posts/index.html.haml
%h1 Listing posts

%table
  %tr
    %th Title
    %th Body
    %th User
    %th
    %th
    %th

  - @posts.each do |post|
    %tr
      %td= post.title
      %td= post.body
      %td= post.user.name
      %td= link_to 'Show', post
      %td= link_to 'Edit', edit_post_path(post)
      %td= link_to 'Destroy', post, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Post', new_post_path

app/views/posts/new.html.haml
%h1 New post

= render 'form'

= link_to 'Back', posts_path

app/views/posts/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @post.title
%p
  %b Body:
  = @post.body
%p
  %b User:
  = @post.user

= link_to 'Edit', edit_post_path(@post)
\|
= link_to 'Back', posts_path

app/views/projects/_form.html.haml
= form_for @project do |f|
  -if @project.errors.any?
    #error_explanation
      %h2= "#{pluralize(@project.errors.count, "error")} prohibited this project from being saved:"
      %ul
        - @project.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :about
    = f.text_area :about
  .field
    = f.label :url
    = f.text_field :url
  .field
    = f.label :source_url
    = f.text_field :source_url
  .field
    = f.label :skills
    = f.text_area :skills
  .field
    = f.label :author
    = f.text_field :author
  .field
    = f.label :status
    = f.text_field :status
  .actions
    = f.submit 'Save'

app/views/projects/edit.html.haml
%h1 Editing project

= render 'form'

= link_to 'Show', @project
\|
= link_to 'Back', projects_path

app/views/projects/index.html.haml
%h1 Listing projects

%table
  %tr
    %th Name
    %th About
    %th Url
    %th Source url
    %th Skills
    %th Author
    %th Status
    %th
    %th
    %th

  - @projects.each do |project|
    %tr
      %td= project.name
      %td= project.about
      %td= project.url
      %td= project.source_url
      %td= project.skills
      %td= project.author
      %td= project.status
      %td= link_to 'Show', project
      %td= link_to 'Edit', edit_project_path(project)
      %td= link_to 'Destroy', project, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Project', new_project_path

app/views/projects/new.html.haml
%h1 New project

= render 'form'

= link_to 'Back', projects_path

app/views/projects/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @project.name
%p
  %b About:
  = @project.about
%p
  %b Url:
  = @project.url
%p
  %b Source url:
  = @project.source_url
%p
  %b Skills:
  = @project.skills
%p
  %b Author:
  = @project.author
%p
  %b Status:
  = @project.status

= link_to 'Edit', edit_project_path(@project)
\|
= link_to 'Back', projects_path

app/views/shared/stream/_event.haml
%li{:class => stream.type }
  = raw t(:event, :scope => [:messages, :stream], :user_name => stream.user.name, :event_name => stream.event.name)

app/views/shared/stream/_post.haml
%li{:class => stream.type }
  = raw t(:post, :scope => [:messages, :stream], :user_name => stream.user.name, :title => stream.post.title)

app/views/shared/stream/_user.haml
%li{:class => stream.type }
  = raw t(:user, :scope => [:messages, :stream], :user_name => stream.user.name)